// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ai/chat": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "AI 流式对话（SSE）",
                "parameters": [
                    {
                        "description": "对话请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE 流式响应",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/ai/models": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "获取 AI 提供商的可用模型列表",
                "parameters": [
                    {
                        "description": "提供商接口信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FetchModelsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/ai/providers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "获取 AI 服务提供商列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.AIProvider"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "添加 AI 服务提供商",
                "parameters": [
                    {
                        "description": "提供商信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIProvider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/ai/providers/test": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "测试 AI 服务提供商连接",
                "parameters": [
                    {
                        "description": "提供商信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIProvider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/ai/providers/{name}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "更新 AI 服务提供商",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "提供商信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AIProvider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "删除 AI 服务提供商",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提供商名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "密码登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/auth/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "设置或修改密码",
                "parameters": [
                    {
                        "description": "密码信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/categories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大类"
                ],
                "summary": "获取所有大类及其匹配规则",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Category"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大类"
                ],
                "summary": "更新分类规则",
                "parameters": [
                    {
                        "description": "分类列表",
                        "name": "categories",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Category"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/check-update": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "检查是否有新版本",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/data/export": {
            "get": {
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "数据管理"
                ],
                "summary": "导出数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/data/import": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据管理"
                ],
                "summary": "导入数据",
                "parameters": [
                    {
                        "type": "file",
                        "description": "导出的 zip 文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否合并日志（true=合并，false=替换）",
                        "name": "merge_logs",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "是否导入配置",
                        "name": "import_config",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "导入的配置类型，可选：basic/auth/ai/categories/webhooks",
                        "name": "import_config_types",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/event-bindings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "事件"
                ],
                "summary": "获取事件绑定列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.EventBinding"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "事件"
                ],
                "summary": "更新事件绑定",
                "parameters": [
                    {
                        "description": "事件绑定列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.EventBinding"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "事件"
                ],
                "summary": "获取事件定义列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "服务健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/logs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "查询日志列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期 YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "事项类型",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "大类名称",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PageResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "新增日志条目",
                "parameters": [
                    {
                        "description": "日志内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LogEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.LogEntryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/logs/event-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "获取所有事项类型",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/logs/timeline": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "获取某天时间轴",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期 YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.LogEntryResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/logs/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "获取单条日志",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "日志ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.LogEntryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "修改日志条目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "日志ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "日志内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LogEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.LogEntryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "删除日志条目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "日志ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/scheduled-tasks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "获取定时任务列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "更新定时任务",
                "parameters": [
                    {
                        "description": "任务配置列表",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ScheduledTaskConfig"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/scheduled-tasks/{name}/run": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时任务"
                ],
                "summary": "手动执行定时任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "获取系统配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设置"
                ],
                "summary": "更新系统配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/statistics/daily": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取某天的统计数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期 YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.DailyStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/statistics/monthly": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取某月的统计数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年份",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "月份",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PeriodStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/statistics/trend": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取日期范围内每天的分类汇总",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.TrendStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/statistics/weekly": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "统计"
                ],
                "summary": "获取某天所在周的统计数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期 YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PeriodStatistics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/system/monitor": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取服务器资源监控",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.SystemMonitor"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取版本信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/webhooks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "获取 webhook 列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Webhook"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "创建 webhook",
                "parameters": [
                    {
                        "description": "Webhook 配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Webhook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/webhooks/test-dry": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "测试未保存的 webhook",
                "parameters": [
                    {
                        "description": "Webhook 配置 + 可选事件名",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/webhooks/{name}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "更新 webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook 名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Webhook 配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Webhook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "删除 webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook 名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/webhooks/{name}/test": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhook"
                ],
                "summary": "测试 webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook 名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "可选指定事件 {\\",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AIChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "model.AIChatRequest": {
            "type": "object",
            "required": [
                "end_date",
                "message",
                "start_date"
            ],
            "properties": {
                "categories": {
                    "description": "可选，筛选指定分类的日志",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AIChatMessage"
                    }
                },
                "message": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "provider_name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                }
            }
        },
        "model.AIProvider": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "default": {
                    "type": "boolean"
                },
                "endpoint": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Category": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CategoryRule"
                    }
                }
            }
        },
        "model.CategoryRule": {
            "type": "object",
            "properties": {
                "pattern": {
                    "type": "string"
                },
                "type": {
                    "description": "\"fixed\" 或 \"regex\"",
                    "type": "string"
                }
            }
        },
        "model.CategorySummary": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "display": {
                    "type": "string"
                },
                "duration": {
                    "description": "总秒数",
                    "type": "integer"
                },
                "percentage": {
                    "description": "占比",
                    "type": "number"
                }
            }
        },
        "model.CrossDayHint": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "direction": {
                    "description": "\"prev\" = 卡片在前一天, \"next\" = 卡片在后一天",
                    "type": "string"
                },
                "end_time": {
                    "description": "在本天的结束时间",
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "start_time": {
                    "description": "在本天的起始时间",
                    "type": "string"
                }
            }
        },
        "model.DailyStatistics": {
            "type": "object",
            "properties": {
                "cross_day_hints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CrossDayHint"
                    }
                },
                "date": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DurationItem"
                    }
                },
                "prev_day_last_time": {
                    "description": "前一天最后一条日志的时间",
                    "type": "string"
                },
                "summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CategorySummary"
                    }
                },
                "time_point_mode": {
                    "type": "string"
                },
                "total_known": {
                    "description": "已知时长总秒数",
                    "type": "integer"
                }
            }
        },
        "model.DayBreakdown": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CategorySummary"
                    }
                },
                "total_known": {
                    "type": "integer"
                }
            }
        },
        "model.DirInfo": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean"
                },
                "file_count": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "model.DurationItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "cross_day": {
                    "description": "跨天任务",
                    "type": "boolean"
                },
                "display": {
                    "description": "可读格式 \"1h30m\"",
                    "type": "string"
                },
                "duration": {
                    "description": "秒",
                    "type": "integer"
                },
                "end_time": {
                    "description": "HH:mm",
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "start_time": {
                    "description": "HH:mm",
                    "type": "string"
                },
                "time_point_mode": {
                    "description": "该条目创建时的模式",
                    "type": "string"
                },
                "unknown": {
                    "description": "首条/末条未知时长",
                    "type": "boolean"
                }
            }
        },
        "model.EventBinding": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "event": {
                    "type": "string"
                },
                "webhook_name": {
                    "type": "string"
                }
            }
        },
        "model.FetchModelsRequest": {
            "type": "object",
            "required": [
                "endpoint"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.LogEntryRequest": {
            "type": "object",
            "required": [
                "event_type",
                "log_time"
            ],
            "properties": {
                "detail": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "log_date": {
                    "description": "可选，默认今天",
                    "type": "string"
                },
                "log_time": {
                    "description": "必填，支持多种格式",
                    "type": "string"
                }
            }
        },
        "model.LogEntryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "log_date": {
                    "type": "string"
                },
                "log_time": {
                    "type": "string"
                },
                "time_point_mode": {
                    "type": "string"
                },
                "time_range": {
                    "type": "string"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "model.PageResult": {
            "type": "object",
            "properties": {
                "items": {},
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.PasswordRequest": {
            "type": "object",
            "required": [
                "new_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 4
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "model.PeriodStatistics": {
            "type": "object",
            "properties": {
                "day_count": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DurationItem"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "summary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CategorySummary"
                    }
                },
                "total_known": {
                    "type": "integer"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ScheduledTaskConfig": {
            "type": "object",
            "properties": {
                "cron": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "model.SystemMonitor": {
            "type": "object",
            "properties": {
                "cpu_cores": {
                    "type": "integer"
                },
                "cpu_usage": {
                    "description": "OS 级别",
                    "type": "number"
                },
                "directories": {
                    "description": "目录信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DirInfo"
                    }
                },
                "disk_percent": {
                    "type": "number"
                },
                "disk_total": {
                    "type": "integer"
                },
                "disk_used": {
                    "description": "磁盘",
                    "type": "integer"
                },
                "go_gc_count": {
                    "type": "integer"
                },
                "go_gc_pause_ms": {
                    "type": "number"
                },
                "go_mem_alloc": {
                    "description": "进程级别（Go runtime）",
                    "type": "integer"
                },
                "go_mem_gc_sys": {
                    "type": "integer"
                },
                "go_mem_sys": {
                    "type": "integer"
                },
                "go_version": {
                    "type": "string"
                },
                "goroutines": {
                    "type": "integer"
                },
                "os_mem_percent": {
                    "type": "number"
                },
                "os_mem_total": {
                    "type": "integer"
                },
                "os_mem_used": {
                    "type": "integer"
                },
                "uptime_seconds": {
                    "description": "运行时间",
                    "type": "integer"
                }
            }
        },
        "model.TrendStatistics": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DayBreakdown"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "model.Webhook": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "query_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timeout_seconds": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lifelog API",
	Description:      "无压力每日事项记录系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
